# Generated by Django 4.2 on 2026-03-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_muted',
            field=models.BooleanField(default=False, verbose_name='是否被禁言'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('mod', '管理员'), ('owner', '网站拥有者')], default='user', max_length=10, verbose_name='用户角色'),
        ),
    ]
